### ISSUE TITLE
Issue can't run

### ISSUE THREAD

**Issue by gravataLonga** [martiis/bitbucket-cli#1]
`PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "Symfony\Component\Console\Application" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. in /vendor/symfony/dependency-injection/Container.php:269
Stack trace:
#0 vendor/symfony/dependency-injection/Container.php(225): Symfony\Component\DependencyInjection\Container->make()
#1 vendor/symfony/dependency-injection/ContainerBuilder.php(555): Symfony\Component\DependencyInjection\Container->get()
#2 /bin/bitbucket(34): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#3 {main}
  thrown in /vendor/symfony/dependency-injection/Container.php on line 269`

The solution is only to put `setPublic()` here:  
`$container
    ->register(Application::class, Application::class)
    ->setArguments(['Bitbucket command line tool', '0.1'])
    ->setPublic(true);`

**Comment by martiis** [comment]
Hi, this project was built in a matter of minutes many time ago :D and I haven't used it in a past year. Lots of things happened in symfony :)

Thanks for the issue

**Comment by gravataLonga** [comment]
But hey, thank for the repo, because help me a lot, the only issue was that. :) I don't so much fan of push request, only open an issue.
